---
apiVersion: k8s.io/v1
kind: Function
metadata:
  name: function1
spec:
  handler: hello.foobar
  runtime: python2.7
  function: |
      import json
      def foobar():
              return "hello world"
